apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.name }}-development
  namespace: argocd
  labels:
    app.kubernetes.io/name: ${{ values.name }}
    app.kubernetes.io/component: workload
    app.kubernetes.io/part-of: tuskerblueprint
    app.kubernetes.io/environment: development
  annotations:
    argocd.argoproj.io/sync-wave: "80"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: workloads
  source:
    repoURL: https://github.com/${{ values.repoUrl | parseRepoUrl | pick('owner') }}/${{ values.repoUrl | parseRepoUrl | pick('repo') }}.git
    targetRevision: main
    path: deploy/overlays/development
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.name }}-development
  revisionHistoryLimit: 10
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        platform.stonetusker.com/workload: "true"
        app.kubernetes.io/environment: development
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
