apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: subeeshes
  title: Subeesh
  description: TuskerBlueprint platform owner
spec:
  profile:
    displayName: Subeesh
  memberOf:
    - platform-team
