apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: tuskerblueprint-catalog
  title: TuskerBlueprint IDP Catalog
  description: Root catalog location for the TuskerBlueprint Internal Developer Platform
spec:
  type: url
  targets:
    - ./catalog/groups/platform-team.yaml
    - ./catalog/groups/developers.yaml
    - ./catalog/users/subeesh.yaml
    - ./catalog/users/subeeshlearn.yaml
    - ./catalog/domains/platform-engineering.yaml
    - ./catalog/systems/tuskerblueprint.yaml
    - ./catalog/resources/development-cluster.yaml
    - ./catalog/resources/tuskerblueprint-repository.yaml
    - ./catalog/components/backstage.yaml
    - ./catalog/components/argocd.yaml
    - ./catalog/components/traefik.yaml
    - ./catalog/components/cert-manager.yaml
    - ./catalog/components/external-secrets.yaml
    - ./catalog/components/kyverno.yaml
    - ./catalog/components/prometheus.yaml
    - ./catalog/components/grafana.yaml
    - ./catalog/components/loki.yaml
    - ./software-templates/tusker-service/template.yaml
    - https://github.com/stonetusker/tusker-demo-notification-service/blob/main/catalog-info.yaml
