# ==============================================================================
# TuskerBlueprint
# Loki Helm Values
# Environment: Production
# ==============================================================================

loki:
  auth_enabled: false

singleBinary:
  replicas: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
