apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.name }}
spec:
  replicas: 2
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ${{ values.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${{ values.name }}
        app.kubernetes.io/component: api
        backstage.io/kubernetes-id: ${{ values.name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "${{ values.port }}"
        tuskerblueprint.io/release-sha: main
    spec:
      serviceAccountName: ${{ values.name }}
      automountServiceAccountToken: false
{% if values.repoVisibility != 'public' %}
      imagePullSecrets:
        - name: ghcr-pull-secret
{% endif %}
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: ghcr.io/${{ values.repoUrl | parseRepoUrl | pick('owner') }}/${{ values.repoUrl | parseRepoUrl | pick('repo') }}:main
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: ${{ values.port }}
          env:
            - name: SERVICE_NAME
              value: ${{ values.name }}
            - name: APP_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['tuskerblueprint.io/release-sha']
            - name: APP_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/environment']
            - name: DEMO_FAILURE_MODE
              value: none
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
            limits:
              cpu: 500m
              memory: 256Mi
          startupProbe:
            httpGet:
              path: /readyz
              port: http
            failureThreshold: 30
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 64Mi
