apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo-staging
  namespace: argocd
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: tuskerblueprint
    app.kubernetes.io/environment: staging
  annotations:
    argocd.argoproj.io/sync-wave: "46"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: 1.24.4
      helm:
        releaseName: tempo-staging
        valueFiles:
          - $values/platform-services/tempo/values/staging.yaml
    - repoURL: git@github.com:stonetusker/tuskerblueprint.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
