# ==============================================================================
# TuskerBlueprint
# Prometheus Helm Values
# Environment: Staging
# ==============================================================================

server:
  replicaCount: 1
  extraFlags:
    - --enable-feature=exemplar-storage

alertmanager:
  enabled: false

pushgateway:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
