apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: traefik-production
  namespace: argocd

  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: ingress
    app.kubernetes.io/part-of: tuskerblueprint
    app.kubernetes.io/environment: production

  annotations:
    argocd.argoproj.io/sync-wave: "10"

spec:
  project: platform

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-production

  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 37.1.0
      helm:
        releaseName: traefik-production
        valueFiles:
          - $values/platform-services/traefik/values/production.yaml
    - repoURL: git@github.com:stonetusker/tuskerblueprint.git
      targetRevision: main
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
