# ==============================================================================
# TuskerBlueprint
# External Secrets Operator Helm Values
# Environment: Staging
# ==============================================================================

replicaCount: 1

serviceAccount:
  create: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
