---
- name: Validate Platform Hosts
  hosts: all
  gather_facts: true

  tasks:
    - name: Verify supported operating system
      ansible.builtin.assert:
        that:
          - ansible_distribution == "Ubuntu"
          - ansible_distribution_major_version == "24"
