# ==============================================================================
# TuskerBlueprint
# Traefik Helm Values
# Environment: Development
# ==============================================================================

deployment:
  replicas: 1

ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik

providers:
  kubernetesCRD:
    enabled: true

  kubernetesIngress:
    enabled: true

logs:
  general:
    level: INFO

accessLog:
  enabled: true

metrics:
  prometheus:
    enabled: true

dashboard:
  enabled: false

ports:
  web:
    expose:
      default: true

  websecure:
    expose:
      default: true

service:
  type: LoadBalancer

additionalArguments:
  - "--serversTransport.insecureSkipVerify=false"

globalArguments:
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"

resources:

  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 512Mi

podSecurityContext:
  fsGroup: 65532

securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

persistence:
  enabled: false
