# ==============================================================================
# TuskerBlueprint
# Traefik Helm Values
# Environment: Production
# ==============================================================================

deployment:
  replicas: 2

ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik

providers:
  kubernetesCRD:
    enabled: true

  kubernetesIngress:
    enabled: true

logs:
  general:
    level: INFO

accessLog:
  enabled: true

metrics:
  prometheus:
    enabled: true

dashboard:
  enabled: false

service:
  type: LoadBalancer
