# ==============================================================================
# TuskerBlueprint
# Traefik Helm Values
# Environment: Staging
# ==============================================================================

deployment:
  replicas: 1

nameOverride: traefik-staging
fullnameOverride: traefik-staging

ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik-staging

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

logs:
  general:
    level: INFO

accessLog:
  enabled: true

metrics:
  prometheus:
    enabled: true

dashboard:
  enabled: false

service:
  type: ClusterIP

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 750m
    memory: 768Mi

podSecurityContext:
  fsGroup: 65532
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
