apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${{ values.name }}-production
resources:
  - ../../base
replicas:
  - name: ${{ values.name }}
    count: 3
commonLabels:
  app.kubernetes.io/environment: production
