apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${{ values.name }}-development
resources:
  - ../../base
images:
  - name: ghcr.io/${{ values.repoUrl | parseRepoUrl | pick('owner') }}/${{ values.repoUrl | parseRepoUrl | pick('repo') }}
    newName: ghcr.io/${{ values.repoUrl | parseRepoUrl | pick('owner') }}/${{ values.repoUrl | parseRepoUrl | pick('repo') }}
    newTag: main
replicas:
  - name: ${{ values.name }}
    count: 2
commonLabels:
  app.kubernetes.io/environment: development
commonAnnotations:
  tuskerblueprint.io/release-sha: main
