apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-github-credentials
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: REPLACE_WITH_SECRET_STORE
    kind: ClusterSecretStore
  target:
    name: backstage-github-credentials
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: backstage/github
        property: readToken
    - secretKey: GITHUB_SCAFFOLDER_TOKEN
      remoteRef:
        key: backstage/github
        property: scaffolderToken
