---
- name: Ensure systemd-timesyncd is installed
  ansible.builtin.apt:
    name: systemd-timesyncd
    state: present

- name: Ensure systemd-timesyncd is enabled and running
  ansible.builtin.service:
    name: systemd-timesyncd
    enabled: true
    state: started
