apiVersion: v1
items:
- apiVersion: v1
  data:
    password: ckRGNHBsVUNFY1dGcGNtZg==
  kind: Secret
  metadata:
    creationTimestamp: "2026-07-04T14:11:44Z"
    name: argocd-initial-admin-secret
    namespace: argocd
    resourceVersion: "2068"
    uid: 5c3d7984-b9a0-4c4a-bc1a-07b44a775322
  type: Opaque
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"notifications-controller","app.kubernetes.io/name":"argocd-notifications-controller","app.kubernetes.io/part-of":"argocd"},"name":"argocd-notifications-secret","namespace":"argocd"},"type":"Opaque"}
    creationTimestamp: "2026-07-04T14:11:27Z"
    labels:
      app.kubernetes.io/component: notifications-controller
      app.kubernetes.io/name: argocd-notifications-controller
      app.kubernetes.io/part-of: argocd
    name: argocd-notifications-secret
    namespace: argocd
    resourceVersion: "1858"
    uid: d2612140-6208-47d6-ba21-0c461dc5693f
  type: Opaque
- apiVersion: v1
  data:
    auth: WjlUVTRuckZGY1dIcXNLcQ==
  kind: Secret
  metadata:
    creationTimestamp: "2026-07-04T14:11:43Z"
    name: argocd-redis
    namespace: argocd
    resourceVersion: "2032"
    uid: 51492e0b-f94c-44ac-9cc4-620a71c7204d
  type: Opaque
- apiVersion: v1
  data:
    admin.password: JDJhJDEwJEZKb0dQQkg0d2wzMzJCd3ZRei9Ud2U2REpyekQxWWQzcC92Qms0OGdTSmlFY3FVTVE1LmpL
    admin.passwordMtime: MjAyNi0wNy0wNFQxNDoxMTo0NFo=
    server.secretkey: OTFZMWsvMGpzK0F4aUI3dUN4bzFKenpsSjh3WXFkTHg1b2JXK2hneVJoOD0=
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURZekNDQWt1Z0F3SUJBZ0lSQU1FclY1bmpET3VsTTRmNXdoeVRtL2d3RFFZSktvWklodmNOQVFFTEJRQXcKRWpFUU1BNEdBMVVFQ2hNSFFYSm5ieUJEUkRBZUZ3MHlOakEzTURReE5ERXhORFJhRncweU56QTNNRFF4TkRFeApORFJhTUJJeEVEQU9CZ05WQkFvVEIwRnlaMjhnUTBRd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3CmdnRUtBb0lCQVFDZlM3cC8rV0U5THJBNXFwY0ZSanl1MzRjTFZ5dFk3UUNhRkJGWWZlb1RlemdwTUFMSnhuNjQKYXF3VFFYNkZQVVhrMDBPSldoZXFTNVBuS0xpeDA4akk0ZE56bE95eEE5YytWZzVMZUUweTFyZmJsY0pJbmViMwpjblFPZEF0SVZ4Vk1VR1kwNW1Ka2hpZHJycmU5cW9hRzMzSzNxWExNclpKVk9zSU56dW0xa21PZzRwM3NtNlZzCnBHRGxPcHB3Q0VtNE9GcDN2c3lzSCtxMWRTNXl1d0NtZ2dEd2ZBdFM0clBXbGhVNUVqTmMzK1VUcDFRMWhHb2UKbm0yUU5xRjE1VUhqNkJDQ1oyY0VtdkNBQkJXOEh6THRWSG5yTVg1b3JhL0M2NXBNdXhxWEJFUnBtaEg2ZzUrYQpFYVEzbWZTdHlrR2UwUlZTclg5RmRhaHFYUm1aK2hUOUFnTUJBQUdqZ2JNd2diQXdEZ1lEVlIwUEFRSC9CQVFECkFnV2dNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01CTUF3R0ExVWRFd0VCL3dRQ01BQXdld1lEVlIwUkJIUXcKY29JSmJHOWpZV3hvYjNOMGdnMWhjbWR2WTJRdGMyVnlkbVZ5Z2hSaGNtZHZZMlF0YzJWeWRtVnlMbUZ5WjI5agpaSUlZWVhKbmIyTmtMWE5sY25abGNpNWhjbWR2WTJRdWMzWmpnaVpoY21kdlkyUXRjMlZ5ZG1WeUxtRnlaMjlqClpDNXpkbU11WTJ4MWMzUmxjaTVzYjJOaGJEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFTeU1vb2NuYkczalUKSVRVQTladm1WeEY5RHVrcThMV3VjdGNoWDlvMk9FMTNBNWUrekNNRmkyRWpQd05hNHlTSUVKMTE5NGxveFV6QwpVTmJIMnpNK0NLSS9NNDJQVHVrL0hzcEV3K1VGS1BvWFFSTTdDVngvajJjNHUrbEVHVkE5QXA4TnVQZVc4dTJ5CmxndGtLVisxK0RBT3ROdnZZSkVrTmlIakxVOTkvY254M0JJV0NPenVSUTZEckJ2b1BHN1RzZUhkVU01c2RFMmoKL0RFM2tDSmkwaFY5OTN1ODRCNk9UWUxXdXYvYyttWmYrc3o4VDY0bGpPRE14Yy9KKzZSWlZGR0ZwYmZ2RlhwZQp4dFRhdUlpQk82enR5TEV4VXNLb3pkN0hnSGlITEt6SnVnbUJVOS9DUW1NV2UvM1VYV1huUDh4eElkSkpCZ3pmClNpRk5KSG8wVVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBbjB1NmYvbGhQUzZ3T2FxWEJVWThydCtIQzFjcldPMEFtaFFSV0gzcUUzczRLVEFDCnljWit1R3FzRTBGK2hUMUY1Tk5EaVZvWHFrdVQ1eWk0c2RQSXlPSFRjNVRzc1FQWFBsWU9TM2hOTXRhMzI1WEMKU0ozbTkzSjBEblFMU0ZjVlRGQm1OT1ppWklZbmE2NjN2YXFHaHQ5eXQ2bHl6SzJTVlRyQ0RjN3B0Wkpqb09LZAo3SnVsYktSZzVUcWFjQWhKdURoYWQ3N01yQi9xdFhVdWNyc0Fwb0lBOEh3TFV1S3oxcFlWT1JJelhOL2xFNmRVCk5ZUnFIcDV0a0RhaGRlVkI0K2dRZ21kbkJKcndnQVFWdkI4eTdWUjU2ekYrYUsydnd1dWFUTHNhbHdSRWFab1IKK29PZm1oR2tONW4wcmNwQm50RVZVcTEvUlhXb2FsMFptZm9VL1FJREFRQUJBb0lCQUMwUmtleVBNL0hKZWRaMgo2MDkwdGNxTU4zci82S1c2T0VkZmtpREZUeXEvMi8zYk5ZNjgrREZaRE9KTnoyd0hEL1ZUeUhIZDZZQW03ZXVpCjI4NkVLdlNhMytaOXBoSFhFbGp5cEF5Nk5xMUJqcmN6d2NvbDBxa0QyczRVQ3ZVbW5rSC9KVXVtT3dSUjZHbFEKLzI5TUJjKzIvSS8yQXlMaG9OczRTcHI1aGFuM0ZKT0JDKzVTMTAxbEgra0VpNDRkRlErL3p3VHlmRm93VjhmWgpodlNCVWwxd1lna245MEU3R0FOWWg2R2VLRWdVdjh0SlI2ZUZzbk5zMGdaWTRkN3ZrNWIxTTBiUHBvQ1Q4M1dHClpLNmJlR3g2N0VMbUlENFNpQlBPZmp6Y2IxSTc0dGIyeDVERXlGeUJTenIvdEhZdVNIUW9VeEJLZ3BqZk1SaWUKd3AwQ0hna0NnWUVBMHhFTWRvMlhhSEVPSWNGbkFPNW85cS9QVjlDbytLN3NCd3FaVXRDbmRMcUpnd0prWEpHeQo5eXJnT08vY2YwcGwyYlVsSmtyaGQ2MytCSWp0bThIUWlPMC9Sb0xMTEZOMWp6c2lxTStKekpaTStqVkRCYTNKCmpLR3Y4YWM0TFp5ekIxN2J2K3ZlWDY3TXU5Zldha3lwNmhpY3BwT1VUVHNZcmo1WXFPWFBwd2NDZ1lFQXdUVTMKUnNhY0hXUG5Jbm5Ialc0c2pHM0Q5UGxMeEJNZUtJZ1RkWnBKSWFEOXQ5QXdDQmYvTkN4MlZrNUVFRVRGKzFwbwpMcnZlZXlMbjlvNTNSV0dwNzVNYWhoSUQ3TzQvVHR2Q2pTSjdadFp4MDRTL1dSeEZmNkR2YXpCZUs1aEdTZlArCjMxVGNTMXhTVGJ6QVgxd2xUYkFjVDBKWlRQR3VHc2tVL2JMcHZ0c0NnWUJYWnpEMUN3OU85Ym8zYWtLQVZUbnMKSmNQRUJxbGlTZlY5dVByakczcXMwTzVPN1Rlb1NjR0ZyeUNwRTFNSTkwTVVFM3B0MEFac0xBWUwxTFFva3VzTApPTXZDSkRtRWdvOGxJQVRyU1A0MFZXMU5FNjlNYzdvSjNZN2hrRENvV3NLY1k4QzJTak9OQmZMTU9zWVV3T2lBCkEyOGpYK3ZDeTUwZDByMmVPNFJ4RXdLQmdHNHlMdlBVSlloeHlZdVZUNmF2MXdMRlBFWEZ4bHZ2MTN5Z21CQzAKVGMrN1pkcG9DRzBsV3E1a1NaNVNCMm9MLzZ1cjFjNEo0d3Z5VGNFSFlxbVUyWHJHT1JPTXhPWm13SDcyd3BFQwp3TVZYdkJZN0dYUDJ0d0RqUm9xcFRKeXF2alJCMFBXS0RoZUJjWVBiQ3hHWW1jSWtseER4czhNNStPWllGL3ZYCkJwQ1BBb0dCQUlYOUxPTE1udkwwMkh0OVdKeDBsa0NIWE9PTXJTdzQ1RjJWSmV6R3phaktzMkp3Qzd5dFhqWkkKdVVpdnFSMW1Yek9HdkFuRENJYm05aGVza3lhUHBGT1hqOTduMVRSTi8rZVBPbDBaVEhyODBxR1Z4bUN5RWpHSgpDK3hsdTlBQ3Rrb3BQcmYrSXNBcXBMclhkNVZ5S0Iwc1p0QXlWS1JDVlJIWm9KcUxHYTA2Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-secret","app.kubernetes.io/part-of":"argocd"},"name":"argocd-secret","namespace":"argocd"},"type":"Opaque"}
    creationTimestamp: "2026-07-04T14:11:27Z"
    labels:
      app.kubernetes.io/name: argocd-secret
      app.kubernetes.io/part-of: argocd
    name: argocd-secret
    namespace: argocd
    resourceVersion: "2074"
    uid: b005214b-8b38-4da1-aeb5-000bacb630d8
  type: Opaque
- apiVersion: v1
  data:
    sshPrivateKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNDdlIwWFhySlpNZzYydTJyMkVGbWVtSWs1NTVNV245bzJKdGl3Q2Joc2hqd0FBQUtCY09SRTBYRGtSCk5BQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQ3ZSMFhYckpaTWc2MnUycjJFRm1lbUlrNTU1TVduOW8ySnRpd0NiaHNoancKQUFBRUE2TlNTYXllK0ZFTnpJVCtscjhFaXZqRmttYUhhWi9mZnBWZWxEckdMTTFxOUhSZGVzbGt5RHJhN2F2WVFXWjZZaQpUbm5reGFmMmpZbTJMQUp1R3lHUEFBQUFGbUZ5WjI5alpFQjBkWE5yWlhKaWJIVmxjSEpwYm5RQkFnTUVCUVlICi0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo=
    type: Z2l0
    url: Z2l0QGdpdGh1Yi5jb206c3RvbmV0dXNrZXIvdHVza2VyYmx1ZXByaW50LmdpdA==
  kind: Secret
  metadata:
    annotations:
      managed-by: argocd.argoproj.io
    creationTimestamp: "2026-07-06T10:10:02Z"
    labels:
      argocd.argoproj.io/secret-type: repository
    name: repo-838497300
    namespace: argocd
    resourceVersion: "49603"
    uid: e33d0ad0-cdc9-41d0-8d6c-8e4379e40b52
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
