---
- name: Check whether k3s is installed
  ansible.builtin.stat:
    path: /usr/local/bin/k3s
  register: k3s_binary

- name: Install k3s
  ansible.builtin.shell: >
    curl -sfL https://get.k3s.io |
    INSTALL_K3S_VERSION={{ k3s_version }}
    INSTALL_K3S_EXEC="server {{ k3s_install_args | join(' ') }}"
    sh -
  args:
    executable: /bin/bash
  when: not k3s_binary.stat.exists

- name: Ensure k3s service is enabled
  ansible.builtin.service:
    name: k3s
    enabled: true
    state: started

- name: Wait for Kubernetes API
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: 6443
    delay: 5
    timeout: 300
