apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: TuskerBlueprint Platform Services

  sourceRepos:
    - 'https://traefik.github.io/charts'
    - 'https://charts.jetstack.io'
    - 'https://charts.external-secrets.io'
    - 'https://helm.doppler.com'
    - 'https://kyverno.github.io/kyverno/'
    - 'git@github.com:stonetusker/tuskerblueprint.git'

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  orphanedResources:
    warn: true
