apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  title: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ${{ values.repoUrl | parseRepoUrl | pick('owner') }}/${{ values.repoUrl | parseRepoUrl | pick('repo') }}
    argocd/app-name: ${{ values.name }}-development
    argocd/instance-name: development
    backstage.io/kubernetes-id: ${{ values.name }}
    backstage.io/kubernetes-namespace: ${{ values.name }}-development
  tags:
    - fastapi
    - devsecops
    - kubernetes
    - gitops
    - techdocs
  links:
    - url: http://localhost:8082/
      title: Local application UI after port-forward
      icon: web
    - url: http://localhost:3000/d/tusker-service-overview/tusker-service-overview?var-environment=development&var-service=${{ values.name }}
      title: Service dashboard in Grafana
      icon: dashboard
    - url: https://github.com/${{ values.repoUrl | parseRepoUrl | pick('owner') }}/${{ values.repoUrl | parseRepoUrl | pick('repo') }}/actions
      title: Delivery workflow
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: ${{ values.system }}
  providesApis:
    - ${{ values.name }}-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.name }}-api
  title: ${{ values.name }} API
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: ${{ values.system }}
  definition:
    $text: ./openapi.yaml
