site_name: ${{ values.name }}
site_description: ${{ values.description }}
repo_url: https://github.com/${{ values.repoUrl | parseRepoUrl | pick('owner') }}/${{ values.repoUrl | parseRepoUrl | pick('repo') }}
edit_uri: edit/main/docs/
docs_dir: docs
nav:
  - Overview: index.md
  - Architecture: architecture.md
  - Development: development.md
  - CI/CD and GitOps: delivery.md
  - Operations: runbook.md
  - Observability: observability.md
  - Security: security.md
plugins:
  - techdocs-core
