apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tuskerblueprint-development-cluster
  title: TuskerBlueprint Development Cluster
  description: Kubernetes cluster used for the development portfolio environment
  tags:
    - kubernetes
    - development
spec:
  type: kubernetes-cluster
  owner: group:default/platform-team
  system: tuskerblueprint
