apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tuskerblueprint-repository
  title: TuskerBlueprint Git Repository
  description: Private GitHub repository that stores the platform desired state
  links:
    - url: https://github.com/stonetusker/tuskerblueprint
      title: Source repository
      icon: github
spec:
  type: repository
  owner: group:default/platform-team
  system: tuskerblueprint
