# ==============================================================================
# TuskerBlueprint
# Grafana Helm Values
# Environment: Staging
# ==============================================================================

adminUser: admin

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

datasources:
  datasources.yaml:
    apiVersion: 1
    deleteDatasources:
      - name: Prometheus
        orgId: 1
      - name: Loki
        orgId: 1
      - name: Tempo
        orgId: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true
        editable: false
        jsonData:
          timeInterval: 15s
          httpMethod: POST
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki-gateway.monitoring.svc.cluster.local
        editable: false
      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://tempo-staging.monitoring.svc.cluster.local:3200
        editable: false
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            spanStartTimeShift: "-5m"
            spanEndTimeShift: "5m"
            filterByTraceID: true
            filterBySpanID: false
