# ==============================================================================
# TuskerBlueprint
# Grafana Helm Values
# Environment: Staging
# ==============================================================================

adminUser: admin

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
