apiVersion: v1
data:
  argocd-server.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDYzCCAkugAwIBAgIRAJ5RmWRlCuVvB9Xv0D3abr0wDQYJKoZIhvcNAQELBQAw
    EjEQMA4GA1UEChMHQXJnbyBDRDAeFw0yNjA4MTQxNDI4MzdaFw0yNzA4MTQxNDI4
    MzdaMBIxEDAOBgNVBAoTB0FyZ28gQ0QwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
    ggEKAoIBAQDOBmwMlWzX9+OlbLhWWlgFPQVnTTVaMZfMyIlbsdLbvc2Lgfy7WbUT
    iePK7hobLV2GcouvzRjAPh0GETL5NzzpdAcdfYYD35HKa3fUowuq/XqrVxRQDSML
    AW9Z7Ait+bP3mS24zPuQyBMr9j4N9Soh47CqxMYSUg7p18Y+U8bTfEM+v6EFl8YG
    PUvFZljmWxszqmr8oc0DffcunIN4jKkpUy7qhwJjiei7ITitLyoHWQVNaj7xOm2Y
    ViqWDRBHqGNwHGQh3BAQ+YnekQstPhvW04DBidJCR0XPh3Jzb8Ips2uL0f/uDhk5
    YJ1NGI3htrMrcjLA3sxm5anpBctydPxdAgMBAAGjgbMwgbAwDgYDVR0PAQH/BAQD
    AgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwewYDVR0RBHQw
    coIJbG9jYWxob3N0gg1hcmdvY2Qtc2VydmVyghRhcmdvY2Qtc2VydmVyLmFyZ29j
    ZIIYYXJnb2NkLXNlcnZlci5hcmdvY2Quc3ZjgiZhcmdvY2Qtc2VydmVyLmFyZ29j
    ZC5zdmMuY2x1c3Rlci5sb2NhbDANBgkqhkiG9w0BAQsFAAOCAQEAU4W2WzxG17Z0
    Shl6wNghHpiTw6ADIMQmsCZNXh4hMt/6IyQF86yAcQjCkBotHYibdCHlsF6wQPjv
    yrq5LdOa2NSMOFE5hiMbRmTvnGnM+Ce4G7dr2/bNvlZsARAN1Sz8KFvUker96Q/9
    FIqQlvi7ImVNjly36t6cSTQxa/3CYhih52YxgL5T4Yx8zkC64BvddCsrKJbIqzSm
    8XQAXsFmnaHCSAdC+WeePST3x/4yaIkE0j+Z37ULd/NV9iEDNVdSndnJDIW68sgp
    NVoDO+43x6uwye7kwuNu7U6wjo0kJnE5VBb1Hwk/JN7kCyYlpb6BAcS+FMB6B3J7
    lt/4oL9UDg==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: backstage-argocd-ca
  namespace: backstage
