apiVersion: v1
data:
  argocd-server.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDYzCCAkugAwIBAgIRAONCXzZEdJOVoXbFEwirXeQwDQYJKoZIhvcNAQELBQAw
    EjEQMA4GA1UEChMHQXJnbyBDRDAeFw0yNjA4MTgxNDA2MjFaFw0yNzA4MTgxNDA2
    MjFaMBIxEDAOBgNVBAoTB0FyZ28gQ0QwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
    ggEKAoIBAQCwnVw2mQYjMI3R54XIDeI6F6ve3Fya4uJca8xrCBfhYFeMh7bR0CLV
    Nu+xOffeIzpU5FXetf16SLI/w8kFZHDL4MWjZ3L6oqyMlQCG7nR58BSimkRRgKp4
    a/lFkafZ3AXEq2VoZ/iRyUmqCQ7k3h9MiC8QG8UTkcg1U9DyWxB09F3W5zdpsaF1
    zH5qiPzubnoYxSMXRpD+n9p1ZI4S/1f1U4qUpDdmekd463RAn3qC/fvZGYWk8paA
    9eV57i/CM7Amm3SZKCGluY8QEMygK2iqFM8ey3jEYak/K//NPz9p14afavmQ3Rh5
    HsHnXq/aSv0yEgR8XxPr8GusduoLGblRAgMBAAGjgbMwgbAwDgYDVR0PAQH/BAQD
    AgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwewYDVR0RBHQw
    coIJbG9jYWxob3N0gg1hcmdvY2Qtc2VydmVyghRhcmdvY2Qtc2VydmVyLmFyZ29j
    ZIIYYXJnb2NkLXNlcnZlci5hcmdvY2Quc3ZjgiZhcmdvY2Qtc2VydmVyLmFyZ29j
    ZC5zdmMuY2x1c3Rlci5sb2NhbDANBgkqhkiG9w0BAQsFAAOCAQEATiDCZeu3ou2v
    9sz1Smas+MhVWIFSJdZbMiLxaBUZzYhC5f3XE+pekm9/YSkAPwniht1zS7Ggor6L
    ZRCIB164g/JBTb6M1ZeUmzcLHjcnW8FfC6+4IxeTFZTD6nzsLxD+b4aGvIh1TE3R
    pXYYmdWilOD/WNoqqBPEiI+Uj/0FzUFZi6WJd0c56Oi0TQKAOHVoh6TY+O/chOjD
    8LwrT3giS1RmQBUcBJjc9fXg5FWJaHWQPFgA+X4FJeO3BVI9mz/P/lxbJXFQYmp6
    HIIGtUrbG/C10kaDt+Eig94cRk2yrCthcHvAwH/fQp5dlCngJcY2ujbjETdgqN1v
    qV1DFLPfXA==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: backstage-argocd-ca
  namespace: backstage
