apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-techdocs
  namespace: backstage
data:
  techdocs.yaml: |
    techdocs:
      publisher:
        type: local
      storageUrl: http://localhost:7007/api/techdocs
      requestTimeout: 60s
