apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-pull-secret
  namespace: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: kubernetes-platform-secrets
    kind: ClusterSecretStore
  target:
    name: ghcr-pull-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{{ .dockerconfigjson }}'
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: ghcr-pull-credentials
        property: .dockerconfigjson
