apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backstage

resources:
  - ghcr-pull-external-secret.yaml
  - service-account.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - network-policy.yaml
  - argocd-ca-configmap.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/name: backstage
      app.kubernetes.io/part-of: tuskerblueprint
