apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-service-development
  namespace: argocd
  labels:
    app.kubernetes.io/name: demo-service
    app.kubernetes.io/component: workload
    app.kubernetes.io/part-of: tuskerblueprint
    app.kubernetes.io/environment: development
  annotations:
    argocd.argoproj.io/sync-wave: "80"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: workloads
  source:
    repoURL: git@github.com:stonetusker/tuskerblueprint.git
    targetRevision: main
    path: workloads/demo-service/overlays/development
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-service-development
  revisionHistoryLimit: 10
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        platform.stonetusker.com/workload: "true"
        app.kubernetes.io/environment: development
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
