# ==============================================================================
# TuskerBlueprint
# cert-manager Helm Values
# Environment: Production
# ==============================================================================

crds:
  enabled: true

installCRDs: false

replicaCount: 1

global:
  leaderElection:
    namespace: cert-manager

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
