apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - deployment.yaml
  - service.yaml
  - pod-disruption-budget.yaml
  - network-policy.yaml

configMapGenerator:
  - name: demo-service-config
    literals:
      - SERVICE_NAME=demo-service
      - DEMO_FAILURE_MODE=none
      - FAILURE_DELAY_MS=2500

generatorOptions:
  labels:
    app.kubernetes.io/name: demo-service
    app.kubernetes.io/part-of: tuskerblueprint
    backstage.io/kubernetes-id: demo-service

commonLabels:
  app.kubernetes.io/name: demo-service
  app.kubernetes.io/part-of: tuskerblueprint
  app.kubernetes.io/managed-by: argocd
  backstage.io/kubernetes-id: demo-service
