apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: demo-service-default-deny
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: demo-service
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: demo-service-allow-http
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: demo-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - traefik-development
                  - traefik-staging
                  - traefik-production
                  - monitoring
                  - backstage
        - namespaceSelector:
            matchLabels:
              platform.stonetusker.com/workload: "true"
      ports:
        - port: 8000
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: demo-service-allow-approved-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: demo-service
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
        - namespaceSelector:
            matchLabels:
              platform.stonetusker.com/workload: "true"
