apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-service-development
resources:
  - ../../base

images:
  - name: ghcr.io/stonetusker/tuskerblueprint-demo-service
    newName: ghcr.io/stonetusker/tuskerblueprint-demo-service
    newTag: 297dcca0b7222e0c01c8ff1b9c6fa9c1b2d59796

replicas:
  - name: demo-service
    count: 1

configMapGenerator:
  - name: demo-service-config
    behavior: merge
    literals:
      - DEMO_FAILURE_MODE=none
      - FAILURE_DELAY_MS=2500

commonLabels:
  app.kubernetes.io/environment: development

commonAnnotations:
  tuskerblueprint.io/release-sha: 297dcca0b7222e0c01c8ff1b9c6fa9c1b2d59796
