apiVersion: v1
kind: Service
metadata:
  name: alloy
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/name: alloy
  ports:
    - name: otlp-grpc
      port: 4317
      protocol: TCP
      targetPort: 4317
  type: ClusterIP