apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-production
  namespace: argocd
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: tuskerblueprint
    app.kubernetes.io/environment: production
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-production
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 0.14.2
      helm:
        releaseName: external-secrets-production
        valueFiles:
          - $values/platform-services/external-secrets/values/production.yaml
    - repoURL: git@github.com:stonetusker/tuskerblueprint.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
