apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: external-secrets
  title: External Secrets Operator
  description: Synchronizes secret material from an external secret manager into Kubernetes
  annotations:
    argocd/app-name: external-secrets
    argocd/instance-name: development
  tags: [security, secrets]
spec:
  type: service
  lifecycle: production
  owner: group:default/platform-team
  system: tuskerblueprint
