---
name: Backstage

on:
  pull_request:
    paths:
      - "platform-services/backstage/**"
      - ".github/workflows/backstage.yml"

permissions:
  contents: read

jobs:
  backstage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      # Enable when Backstage implementation starts