---
name: Repository CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  repository:
    name: Repository CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate GitHub Actions
        uses: rhysd/actionlint@v1