---
name: GitOps

on:
  pull_request:
    paths:
      - "gitops/**"
      - ".github/workflows/gitops.yml"

  push:
    branches:
      - main
    paths:
      - "gitops/**"

permissions:
  contents: read

jobs:
  gitops:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      # Enable when GitOps manifests are implemented
      #
      # - name: Setup Helm
      #   uses: azure/setup-helm@v4
      #
      # - name: Helm Lint
      #   run: helm lint ...
      #
      # - name: Setup Kustomize
      #   uses: imranismail/setup-kustomize@v2
      #
      # - name: Kustomize Build
      #   run: kustomize build gitops