---
name: Kubernetes

on:
  pull_request:
    paths:
      - "gitops/**"
      - "platform-services/**"
      - ".github/workflows/kubernetes.yml"

  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  kubernetes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Enable when Kubernetes manifests exist
      #
      # - name: Install kubeconform
      #
      # - name: Validate Kubernetes Manifests
      #
      # - name: Validate CRDs