---
name: Security

on:
  pull_request:

  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      # Enable during security implementation
      #
      # - name: Gitleaks
      #
      # - name: Trivy
      #
      # - name: SBOM
      #
      # - name: Cosign