#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
APP_DIR="${1:-${ROOT_DIR}/.generated/backstage}"
RELEASE_FILE="${ROOT_DIR}/backstage-app/backstage-release.txt"
OVERRIDES_DIR="${ROOT_DIR}/backstage-app/overrides"
APP_NAME="${BACKSTAGE_APP_NAME:-tuskerblueprint-backstage}"

for command_name in node npx corepack rsync; do
  command -v "${command_name}" >/dev/null 2>&1 || {
    echo "Required command not found: ${command_name}" >&2
    exit 1
  }
done

if [[ ! -f "${RELEASE_FILE}" ]]; then
  echo "Backstage release file not found: ${RELEASE_FILE}" >&2
  exit 1
fi

if [[ ! -d "${OVERRIDES_DIR}" ]]; then
  echo "Backstage overrides directory not found: ${OVERRIDES_DIR}" >&2
  exit 1
fi

RELEASE="$(tr -d '[:space:]' < "${RELEASE_FILE}")"
NODE_MAJOR="$(node -p "process.versions.node.split('.')[0]")"

if [[ "${NODE_MAJOR}" != "20" ]]; then
  echo "Node.js 20 is required; found $(node --version)" >&2
  exit 1
fi

export COREPACK_ENABLE_DOWNLOAD_PROMPT=0
export YARN_ENABLE_IMMUTABLE_INSTALLS=false
export YARN_ENABLE_SCRIPTS=false

rm -rf "${APP_DIR}"
mkdir -p "$(dirname "${APP_DIR}")"

echo "Creating Backstage application skeleton in ${APP_DIR}"

printf '%s\n' "${APP_NAME}" |
  env -u CI \
    COREPACK_ENABLE_DOWNLOAD_PROMPT=0 \
    YARN_ENABLE_IMMUTABLE_INSTALLS=false \
    YARN_ENABLE_SCRIPTS=false \
    npx --yes @backstage/create-app@latest \
      --path "${APP_DIR}"

pushd "${APP_DIR}" >/dev/null

corepack enable

echo "Node version: $(node --version)"
echo "Yarn version: $(corepack yarn --version)"
echo "Target Backstage release: ${RELEASE}"

echo "Aligning generated Backstage packages"

corepack yarn backstage-cli versions:bump \
  --release "${RELEASE}"

echo "Installing TuskerBlueprint frontend plugins"

corepack yarn --cwd packages/app add \
  @backstage/app-defaults \
  @backstage/plugin-kubernetes \
  @backstage-community/plugin-github-actions \
  @roadiehq/backstage-plugin-argo-cd

echo "Installing TuskerBlueprint backend plugins"

corepack yarn --cwd packages/backend add \
  @backstage/plugin-kubernetes-backend \
  @backstage/plugin-permission-common \
  @backstage/plugin-permission-node \
  @roadiehq/backstage-plugin-argo-cd-backend


echo "Adding node-gyp for native production dependency builds"

#
# node-gyp must be a production dependency at the root workspace.
# ssh2 and cpu-features invoke it during the Docker production install.
#
corepack yarn add node-gyp

# The TuskerBlueprint frontend overrides use the stable frontend API.
# Remove navigation modules generated by newer create-app templates.
rm -rf packages/app/src/modules/nav

echo "Applying TuskerBlueprint application overrides"

rsync -a \
  "${OVERRIDES_DIR}/" \
  "${APP_DIR}/"

echo "Updating the lockfile without running native lifecycle builds"

corepack yarn install \
  --mode=skip-build

echo "Confirming that the generated lockfile is immutable"

YARN_ENABLE_IMMUTABLE_INSTALLS=true \
  corepack yarn install \
    --immutable \
    --mode=skip-build

for required_file in \
  package.json \
  yarn.lock \
  .yarnrc.yml \
  packages/app/package.json \
  packages/backend/package.json \
  packages/backend/Dockerfile; do

  if [[ ! -f "${required_file}" ]]; then
    echo "Generated file is missing: ${APP_DIR}/${required_file}" >&2
    exit 1
  fi
done

popd >/dev/null

echo "Custom Backstage source generated successfully: ${APP_DIR}"
echo
echo "Validation commands:"
echo "  cd ${APP_DIR}"
echo "  corepack yarn tsc"
echo "  corepack yarn workspace app test --ci --runInBand --passWithNoTests"
echo "  corepack yarn workspace backend build"
