apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: traefik
  namespace: argocd

  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/part-of: tuskerblueprint

  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  project: platform

  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 37.1.1
      helm:
        releaseName: traefik
        valueFiles:
          - $values/platform-services/traefik/values/development.yaml

    - repoURL: git@github.com:stonetusker/tuskerblueprint.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
